server:
  port: 8888

spring:
  application:
    name: caderneta-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: ${URL_GITHUB:https://github.com/sironAzevedo/caderneta}
          search-paths:          - caderneta-configurations
#          username: ${GITHUB_USER}
#          password: ${GITHUB_PASS}
    
